### ISSUE TITLE
Better document account changes format and payload

### ISSUE THREAD

**Issue by unity** [hull-ships/hull-processor#59]
User notifications contain a hash of `account` changes when those happen.
They also contain `account_segments`.

The simulated Preview today doesn't display examples of those.

A better preview strategy is being fleshed out but to alleviate immediate needs for transparency, 
we should be refining the docs to better describe the payload that's received by the connector,
and the simulated payload displayed on the Code editor screen

### In the Docs

Describe and document:
- `account_segments` object
- `account` object
- `changes.account` and `changes.account_segments` objects

### In the preview
Simulate a payload for the following objects that aren't displayed today:

- `notification.account_segments` // Display the actual data
- `notification.changes.account` // Simulate by picking random keys like we do for `changes.user`
- `notification.changes.account_segments` // Simulate by picking random account segments.

**Comment by michaloo** [comment]
Progress tracked in https://github.com/hull/hull-connectors-issues/issues/6
